# @package _global_
dataset:
  coeff: 1.0

model:
  encoder:
    optimizer:
      learning_rate: 0.01
    batch_size: 64
    seq_hidden_units: 24
    br_size: 6
    fc_hidden_units: 18
    dropout_rate: 0.2

  train_decoder: True
  decoder:
    optimizer:
      learning_rate: 0.01
    batch_size: 512
    br_size: 6
    fc_hidden_units: 6
    dropout_rate: 0.1

exp:
  weights_ema: True
  alpha: 0.01
  beta: 0.99
  balancing: domain_confusion
  max_epochs: 150