# @package _global_
dataset:
  coeff: 3.0

model:
  encoder:
    optimizer:
      learning_rate: 0.01
    batch_size: 128
    seq_hidden_units: 24
    br_size: 3
    fc_hidden_units: 6
    dropout_rate: 0.1

  train_decoder: True
  decoder:
    optimizer:
      learning_rate: 0.001
    batch_size: 512
    br_size: 3
    fc_hidden_units: 9
    dropout_rate: 0.2

exp:
  weights_ema: True
  alpha: 0.01
  beta: 0.99
  balancing: domain_confusion
  max_epochs: 150